import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import CourseCard from '../components/CourseCard';
import courseList from '../data/courses.json';

function Home(props) {
  console.log(courseList);

  return (
    <div className={styles.container}>
      <Head>
        <title>CSB Flowchart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 styles={styles.title}>CSB Flowchart</h3>

        <div className={styles.grid}>
          {courseList.map((course) =>(
            <CourseCard key={course.title} name={course.title} />
          ))}
        </div>
      </main>
    </div>
  )
}

export default Home;
